#!/usr/bin/env python3
"""Generate the night-sky bright-star catalog (data/stars.csv) from the HYG database.

The HYG database (https://github.com/astronexus/HYG-Database, public domain / CC-BY-SA on some
columns) merges Hipparcos/Yale/Gliese with proper names and constellations — ideal for a labelled
sky. This script downloads it, keeps stars to a magnitude limit (default 6.0 = naked-eye limit),
and writes the compact CSV the app parses (StarCatalog.Parse):

    raHours, decDegrees, magnitude, name, constellation

Run offline when you want to refresh / densify the field:

    python scripts/generate-star-catalog.py --max-mag 6.0 --out data/stars.csv

The committed data/stars.csv is a small curated bright+named set so the feature works before this
runs; this script overwrites it with the full field (still carrying names for labels).
"""
import argparse
import csv
import io
import sys
import urllib.request

HYG_URL = "https://raw.githubusercontent.com/astronexus/HYG-Database/main/hyg/v3/hygdata_v3.csv"

# Three-letter IAU constellation abbreviation -> readable name (subset; extend as needed).
CONSTELLATIONS = {
    "And": "Andromeda", "Aql": "Aquila", "Aqr": "Aquarius", "Ari": "Aries", "Aur": "Auriga",
    "Boo": "Bootes", "Cae": "Caelum", "Cam": "Camelopardalis", "Cap": "Capricornus", "Car": "Carina",
    "Cas": "Cassiopeia", "Cen": "Centaurus", "Cep": "Cepheus", "Cet": "Cetus", "CMa": "Canis Major",
    "CMi": "Canis Minor", "Cnc": "Cancer", "Col": "Columba", "CrB": "Corona Borealis", "Crv": "Corvus",
    "Cyg": "Cygnus", "Dra": "Draco", "Eri": "Eridanus", "Gem": "Gemini", "Her": "Hercules",
    "Hya": "Hydra", "Leo": "Leo", "Lep": "Lepus", "Lib": "Libra", "Lyr": "Lyra", "Oph": "Ophiuchus",
    "Ori": "Orion", "Peg": "Pegasus", "Per": "Perseus", "PsA": "Piscis Austrinus", "Psc": "Pisces",
    "Pup": "Puppis", "Sco": "Scorpius", "Sgr": "Sagittarius", "Tau": "Taurus", "TrA": "Triangulum Australe",
    "UMa": "Ursa Major", "UMi": "Ursa Minor", "Vir": "Virgo", "Vel": "Vela",
}


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate data/stars.csv from the HYG database.")
    ap.add_argument("--max-mag", type=float, default=6.0, help="faintest magnitude to keep (default 6.0)")
    ap.add_argument("--out", default="data/stars.csv", help="output CSV path")
    ap.add_argument("--url", default=HYG_URL, help="HYG hygdata_v3.csv URL")
    args = ap.parse_args()

    print(f"Downloading HYG catalog: {args.url}", file=sys.stderr)
    with urllib.request.urlopen(args.url) as resp:  # noqa: S310 (trusted public catalog)
        text = resp.read().decode("utf-8")

    rows = []
    for r in csv.DictReader(io.StringIO(text)):
        try:
            mag = float(r["mag"])
            ra = float(r["ra"])      # hours
            dec = float(r["dec"])    # degrees
        except (KeyError, ValueError):
            continue
        if mag > args.max_mag:
            continue
        name = (r.get("proper") or "").strip()
        con = CONSTELLATIONS.get((r.get("con") or "").strip(), "")
        rows.append((ra, dec, mag, name, con))

    rows.sort(key=lambda s: s[2])  # brightest first
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("# Bright-star catalog (HYG) — raHours,decDegrees,magnitude,name,constellation (J2000).\n")
        f.write(f"# Generated by scripts/generate-star-catalog.py, mag <= {args.max_mag}, {len(rows)} stars.\n")
        for ra, dec, mag, name, con in rows:
            f.write(f"{ra:.4f},{dec:.4f},{mag:.2f},{name},{con}\n")

    print(f"Wrote {len(rows)} stars to {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
