using System.Buffers.Binary;
using FluentAssertions;
using MapaTur.Domain.Terrain;
using MapaTur.Infrastructure.Terrain;

namespace MapaTur.Infrastructure.Tests.Terrain;

public sealed class DemRasterReaderTests : IDisposable
{
    private readonly string tempPath;

    public DemRasterReaderTests()
    {
        tempPath = Path.Combine(Path.GetTempPath(), $"mapatur-dem-{Guid.NewGuid():N}.dem");
    }

    public void Dispose()
    {
        if (File.Exists(tempPath))
        {
            File.Delete(tempPath);
        }
    }

    private static byte[] BuildDemFile(
        int cols,
        int rows,
        double west,
        double south,
        double east,
        double north,
        float[] samples,
        float nodata = -9999f,
        string magic = "DEM1",
        int version = 1)
    {
        const int headerBytes = 64;
        byte[] result = new byte[headerBytes + (samples.Length * sizeof(float))];
        Span<byte> span = result;
        System.Text.Encoding.ASCII.GetBytes(magic).AsSpan().CopyTo(span);
        BinaryPrimitives.WriteInt32LittleEndian(span[4..], version);
        BinaryPrimitives.WriteInt32LittleEndian(span[8..], cols);
        BinaryPrimitives.WriteInt32LittleEndian(span[12..], rows);
        BinaryPrimitives.WriteDoubleLittleEndian(span[16..], west);
        BinaryPrimitives.WriteDoubleLittleEndian(span[24..], south);
        BinaryPrimitives.WriteDoubleLittleEndian(span[32..], east);
        BinaryPrimitives.WriteDoubleLittleEndian(span[40..], north);
        BinaryPrimitives.WriteSingleLittleEndian(span[48..], nodata);
        for (int i = 0; i < samples.Length; i++)
        {
            BinaryPrimitives.WriteSingleLittleEndian(span[(headerBytes + (i * sizeof(float)))..], samples[i]);
        }

        return result;
    }

    [Fact]
    public void Read_ParsesWellFormedFile()
    {
        var samples = new[] { 100f, 200f, 300f, 400f };
        File.WriteAllBytes(tempPath, BuildDemFile(2, 2, 19.0, 49.0, 20.0, 50.0, samples));

        DemRaster raster = DemRasterReader.Read(tempPath);

        raster.Columns.Should().Be(2);
        raster.Rows.Should().Be(2);
        raster.Bounds.SouthWest.Latitude.Should().Be(49.0);
        raster.Bounds.NorthEast.Longitude.Should().Be(20.0);
        raster[0, 0].Should().Be(100f);
        raster[1, 1].Should().Be(400f);
    }

    [Fact]
    public void Read_ThrowsFileNotFoundForMissingFile()
    {
        var act = () => DemRasterReader.Read(Path.Combine(Path.GetTempPath(), $"missing-{Guid.NewGuid():N}.dem"));

        act.Should().Throw<FileNotFoundException>();
    }

    [Fact]
    public void Read_ThrowsInvalidDataForBadMagic()
    {
        File.WriteAllBytes(tempPath, BuildDemFile(2, 2, 19.0, 49.0, 20.0, 50.0, new float[4], magic: "XXXX"));

        var act = () => DemRasterReader.Read(tempPath);

        act.Should().Throw<InvalidDataException>()
            .WithMessage("*magic*");
    }

    [Fact]
    public void Read_ThrowsInvalidDataForUnsupportedVersion()
    {
        File.WriteAllBytes(tempPath, BuildDemFile(2, 2, 19.0, 49.0, 20.0, 50.0, new float[4], version: 99));

        var act = () => DemRasterReader.Read(tempPath);

        act.Should().Throw<InvalidDataException>()
            .WithMessage("*version*");
    }

    [Fact]
    public void Read_ThrowsInvalidDataForSizeMismatch()
    {
        // Header says 4x4 (64 floats) but only 4 float samples follow.
        byte[] file = BuildDemFile(2, 2, 19.0, 49.0, 20.0, 50.0, new float[4]);
        // Tamper the cols field to 4 (so size mismatch is detected).
        BinaryPrimitives.WriteInt32LittleEndian(file.AsSpan(8), 4);
        BinaryPrimitives.WriteInt32LittleEndian(file.AsSpan(12), 4);
        File.WriteAllBytes(tempPath, file);

        var act = () => DemRasterReader.Read(tempPath);

        act.Should().Throw<InvalidDataException>()
            .WithMessage("*size*");
    }

    [Fact]
    public void Read_LoadsTatryFixtureWithExpectedDimensionsAndRange()
    {
        string fixturePath = Path.Combine(AppContext.BaseDirectory, "testdata", "dem", "tatry.dem");
        File.Exists(fixturePath).Should().BeTrue("tatry.dem fixture must be generated by testdata/maps/generate-tatry-dem.py");

        DemRaster raster = DemRasterReader.Read(fixturePath);

        raster.Columns.Should().Be(256);
        raster.Rows.Should().Be(86);
        raster.Bounds.SouthWest.Latitude.Should().BeApproximately(49.10, 1e-6);
        raster.Bounds.NorthEast.Longitude.Should().BeApproximately(20.40, 1e-6);

        var (min, max) = raster.GetElevationRange();
        min.Should().BeApproximately(700.0, 50.0, "base elevation in the synthetic generator");
        max.Should().BeGreaterThan(2400.0, "synthetic peaks reach Tatra-like heights");
    }
}